### ISSUE TITLE
Always upgrading all casks

### ISSUE THREAD

**Issue by FrankErd** [buo/brew-cask-upgrade#4]
Brew-cask-upgrade is always upgrading all my casks (instead upgrading only the outdated) every time I run it. Since Verion 1.0.0.
Thanks

**Comment by buo** [comment]
The default Caskroom location has moved to `/usr/local/Caskroom` from `/opt/homebrew-cask/Caskroom`. Please update the Homebrew Cask (`brew cask update`) and migrate your Casks to the new location. You can just simply move the legacy directory to the new directory:

```
mv /opt/homebrew-cask/Caskroom /usr/local/Caskroom
```

For more details, see https://github.com/caskroom/homebrew-cask/issues/21913.

**Comment by buo** [comment]
This issue was resolve in [f5b8d8c](https://github.com/buo/homebrew-cask-upgrade/commit/f5b8d8caf302f89b8c3b250d522e60ea1bde2f76#diff-8e18381f4f7441e18a430d432f4313c5).
